# Generated by Django 3.2.4 on 2022-04-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='About',
            field=models.CharField(blank=True, default='User', max_length=450),
            preserve_default=False,
        ),
    ]
